#!/bin/bash -le

export LOG_DIR=/var/vcap/sys/log/lcats
export GOROOT=$(readlink -nf /var/vcap/packages/golang1.12.4)
export PATH="${GOROOT}/bin:/var/vcap/packages/lcats/bin:${PATH}"
export CF_COLOR=false

source /var/vcap/jobs/lcats/bin/environment.sh

cd /var/vcap/packages/lcats

export ADDR="$LOG_EMITTER_ADDR"
exec chpst -u vcap:vcap log-cache-emitter  &> "${LOG_DIR}/log-cache-emitter.log" &

trap "kill -9 $(ps aux -u vcap | grep "log-cache-emitter" | head -n 1 | awk '{print $2}')" EXIT

ginkgo -p bin/lcats.test -r \
  -slowSpecThreshold 30 \
  -progress \
  -trace \
  -keepGoing

exit 0
