#!/bin/bash -l

set -e

export LOG_DIR=/var/vcap/sys/log/lcats
export GOROOT=$(readlink -nf /var/vcap/packages/golang1.9.6)
export GOPATH=/var/vcap/packages/lcats
export PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"
export CF_COLOR=false

source /var/vcap/jobs/lcats/bin/environment.sh

pushd /var/vcap/packages/log-cache-emitter
    export ADDR="$LOG_EMITTER_ADDR"
    exec chpst -u vcap:vcap ./log-cache-emitter &> "${LOG_DIR}/log-cache-emitter.log" &

    trap "kill -9 $(ps aux | grep "./log-cache-emitter" | head -n 1 | awk '{print $2}')" EXIT
popd

cd /var/vcap/packages/lcats/src/github.com/cloudfoundry/log-cache-acceptance-tests

ginkgo build .

ginkgo -p log-cache-acceptance-tests.test -r \
    -slowSpecThreshold 30 \
    -progress \
    -trace \
    -keepGoing

exit 0
