#!/bin/bash
set -e

go get github.com/vito/gosub

if [ ! $(which gosub) ]; then
    echo "Gosub required to update dependencies in bosh/*/spec files."
    echo 'Please install with `go get github.com/vito/gosub`'
    exit 1
fi

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    gosublist=$(gosub list "$@")

    {
      cat spec | grep -v '# gosub'
      for i in $gosublist; do
          echo $i | sed -e 's|\(.*\)|- \1/*.go # gosub|g'

          if ls $GOPATH/src/$i/*.s &> /dev/null; then
              echo $i | sed -e 's|\(.*\)|- \1/*.s # gosub|g'
          fi
      done
    } > spec.new

    mv spec.new spec

  )
}

sync_package log-cache-emitter -app  github.com/cloudfoundry-incubator/log-cache-tools/log-cache-emitter &
sync_package lcats             -app  github.com/cloudfoundry/log-cache-acceptance-tests/tests &

wait
